# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created: Sun Apr 12 19:46:28 2015
#      by: PyQt5 UI code generator 5.4
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.setEnabled(True)
        MainWindow.resize(960, 720)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMaximumSize(QtCore.QSize(16777215, 100))
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lcdNumber_3 = QtWidgets.QLCDNumber(self.groupBox_2)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.lcdNumber_3.setPalette(palette)
        self.lcdNumber_3.setObjectName("lcdNumber_3")
        self.gridLayout_2.addWidget(self.lcdNumber_3, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_2, 1, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 100))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.lcdNumber_2 = QtWidgets.QLCDNumber(self.groupBox)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.lcdNumber_2.setPalette(palette)
        self.lcdNumber_2.setObjectName("lcdNumber_2")
        self.gridLayout.addWidget(self.lcdNumber_2, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox, 2, 0, 1, 1)
        self.pb_hlt = QtWidgets.QGroupBox(self.centralwidget)
        self.pb_hlt.setObjectName("pb_hlt")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.pb_hlt)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_9 = QtWidgets.QLabel(self.pb_hlt)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setObjectName("label_9")
        self.gridLayout_6.addWidget(self.label_9, 0, 0, 1, 1)
        self.lcd_sparge_set = QtWidgets.QLCDNumber(self.pb_hlt)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 158, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 158, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.lcd_sparge_set.setPalette(palette)
        self.lcd_sparge_set.setLineWidth(1)
        self.lcd_sparge_set.setSmallDecimalPoint(False)
        self.lcd_sparge_set.setDigitCount(5)
        self.lcd_sparge_set.setMode(QtWidgets.QLCDNumber.Dec)
        self.lcd_sparge_set.setProperty("value", 70.0)
        self.lcd_sparge_set.setProperty("intValue", 70)
        self.lcd_sparge_set.setObjectName("lcd_sparge_set")
        self.gridLayout_6.addWidget(self.lcd_sparge_set, 5, 0, 1, 1)
        self.sldr_strike_set = QtWidgets.QSlider(self.pb_hlt)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sldr_strike_set.sizePolicy().hasHeightForWidth())
        self.sldr_strike_set.setSizePolicy(sizePolicy)
        self.sldr_strike_set.setMinimum(70)
        self.sldr_strike_set.setMaximum(100)
        self.sldr_strike_set.setOrientation(QtCore.Qt.Vertical)
        self.sldr_strike_set.setObjectName("sldr_strike_set")
        self.gridLayout_6.addWidget(self.sldr_strike_set, 3, 1, 1, 1)
        self.alarmbtn_hlt = QtWidgets.QPushButton(self.pb_hlt)
        self.alarmbtn_hlt.setStyleSheet("background-color: rgb(0, 154, 74);")
        self.alarmbtn_hlt.setCheckable(True)
        self.alarmbtn_hlt.setChecked(False)
        self.alarmbtn_hlt.setAutoRepeat(True)
        self.alarmbtn_hlt.setAutoExclusive(True)
        self.alarmbtn_hlt.setObjectName("alarmbtn_hlt")
        self.gridLayout_6.addWidget(self.alarmbtn_hlt, 6, 0, 1, 2)
        self.alarm_hlt = QtWidgets.QToolButton(self.pb_hlt)
        self.alarm_hlt.setMaximumSize(QtCore.QSize(20, 20))
        self.alarm_hlt.setStyleSheet("background-color: rgb(85, 255, 127);")
        self.alarm_hlt.setObjectName("alarm_hlt")
        self.gridLayout_6.addWidget(self.alarm_hlt, 0, 1, 1, 1)
        self.lcd_strike_set = QtWidgets.QLCDNumber(self.pb_hlt)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 158, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 158, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.lcd_strike_set.setPalette(palette)
        self.lcd_strike_set.setLineWidth(1)
        self.lcd_strike_set.setSmallDecimalPoint(False)
        self.lcd_strike_set.setDigitCount(5)
        self.lcd_strike_set.setMode(QtWidgets.QLCDNumber.Dec)
        self.lcd_strike_set.setProperty("value", 70.0)
        self.lcd_strike_set.setProperty("intValue", 70)
        self.lcd_strike_set.setObjectName("lcd_strike_set")
        self.gridLayout_6.addWidget(self.lcd_strike_set, 3, 0, 1, 1)
        self.lcd_hlt_meas = QtWidgets.QLCDNumber(self.pb_hlt)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcd_hlt_meas.sizePolicy().hasHeightForWidth())
        self.lcd_hlt_meas.setSizePolicy(sizePolicy)
        self.lcd_hlt_meas.setSizeIncrement(QtCore.QSize(0, 0))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.lcd_hlt_meas.setPalette(palette)
        self.lcd_hlt_meas.setProperty("value", 55.0)
        self.lcd_hlt_meas.setObjectName("lcd_hlt_meas")
        self.gridLayout_6.addWidget(self.lcd_hlt_meas, 1, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.pb_hlt)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName("label_7")
        self.gridLayout_6.addWidget(self.label_7, 4, 0, 1, 2)
        self.label_8 = QtWidgets.QLabel(self.pb_hlt)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName("label_8")
        self.gridLayout_6.addWidget(self.label_8, 2, 0, 1, 2)
        self.sldr_sparge_set = QtWidgets.QSlider(self.pb_hlt)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sldr_sparge_set.sizePolicy().hasHeightForWidth())
        self.sldr_sparge_set.setSizePolicy(sizePolicy)
        self.sldr_sparge_set.setMinimum(70)
        self.sldr_sparge_set.setMaximum(100)
        self.sldr_sparge_set.setOrientation(QtCore.Qt.Vertical)
        self.sldr_sparge_set.setObjectName("sldr_sparge_set")
        self.gridLayout_6.addWidget(self.sldr_sparge_set, 5, 1, 1, 1)
        self.gridLayout_3.addWidget(self.pb_hlt, 3, 0, 1, 1)
        self.pb_mash = QtWidgets.QGroupBox(self.centralwidget)
        self.pb_mash.setObjectName("pb_mash")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.pb_mash)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label = QtWidgets.QLabel(self.pb_mash)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 4, 0, 1, 2)
        self.label_4 = QtWidgets.QLabel(self.pb_mash)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 2, 0, 1, 2)
        self.lcd_mash_meas = QtWidgets.QLCDNumber(self.pb_mash)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcd_mash_meas.sizePolicy().hasHeightForWidth())
        self.lcd_mash_meas.setSizePolicy(sizePolicy)
        self.lcd_mash_meas.setSizeIncrement(QtCore.QSize(0, 0))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.lcd_mash_meas.setPalette(palette)
        self.lcd_mash_meas.setProperty("value", 55.0)
        self.lcd_mash_meas.setObjectName("lcd_mash_meas")
        self.gridLayout_4.addWidget(self.lcd_mash_meas, 1, 0, 1, 1)
        self.alarmbtn_mash = QtWidgets.QPushButton(self.pb_mash)
        self.alarmbtn_mash.setStyleSheet("background-color: rgb(0, 154, 74);")
        self.alarmbtn_mash.setCheckable(True)
        self.alarmbtn_mash.setChecked(False)
        self.alarmbtn_mash.setAutoRepeat(True)
        self.alarmbtn_mash.setAutoExclusive(True)
        self.alarmbtn_mash.setObjectName("alarmbtn_mash")
        self.gridLayout_4.addWidget(self.alarmbtn_mash, 6, 0, 1, 2)
        self.lcd_mash_set = QtWidgets.QLCDNumber(self.pb_mash)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 158, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 158, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.lcd_mash_set.setPalette(palette)
        self.lcd_mash_set.setLineWidth(1)
        self.lcd_mash_set.setSmallDecimalPoint(False)
        self.lcd_mash_set.setDigitCount(5)
        self.lcd_mash_set.setMode(QtWidgets.QLCDNumber.Dec)
        self.lcd_mash_set.setProperty("value", 55.0)
        self.lcd_mash_set.setProperty("intValue", 55)
        self.lcd_mash_set.setObjectName("lcd_mash_set")
        self.gridLayout_4.addWidget(self.lcd_mash_set, 3, 0, 1, 1)
        self.lcd_mash_time = QtWidgets.QLCDNumber(self.pb_mash)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.lcd_mash_time.setPalette(palette)
        self.lcd_mash_time.setLineWidth(1)
        self.lcd_mash_time.setSmallDecimalPoint(False)
        self.lcd_mash_time.setDigitCount(5)
        self.lcd_mash_time.setMode(QtWidgets.QLCDNumber.Dec)
        self.lcd_mash_time.setProperty("value", 40.0)
        self.lcd_mash_time.setProperty("intValue", 40)
        self.lcd_mash_time.setObjectName("lcd_mash_time")
        self.gridLayout_4.addWidget(self.lcd_mash_time, 5, 0, 1, 1)
        self.sldr_mash_time = QtWidgets.QSlider(self.pb_mash)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sldr_mash_time.sizePolicy().hasHeightForWidth())
        self.sldr_mash_time.setSizePolicy(sizePolicy)
        self.sldr_mash_time.setMinimum(40)
        self.sldr_mash_time.setMaximum(80)
        self.sldr_mash_time.setOrientation(QtCore.Qt.Vertical)
        self.sldr_mash_time.setObjectName("sldr_mash_time")
        self.gridLayout_4.addWidget(self.sldr_mash_time, 5, 1, 1, 1)
        self.sldr_mash_set = QtWidgets.QSlider(self.pb_mash)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sldr_mash_set.sizePolicy().hasHeightForWidth())
        self.sldr_mash_set.setSizePolicy(sizePolicy)
        self.sldr_mash_set.setMinimum(55)
        self.sldr_mash_set.setMaximum(75)
        self.sldr_mash_set.setOrientation(QtCore.Qt.Vertical)
        self.sldr_mash_set.setObjectName("sldr_mash_set")
        self.gridLayout_4.addWidget(self.sldr_mash_set, 3, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.pb_mash)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 0, 0, 1, 1)
        self.alarm_mash = QtWidgets.QToolButton(self.pb_mash)
        self.alarm_mash.setMaximumSize(QtCore.QSize(20, 20))
        self.alarm_mash.setStyleSheet("background-color: rgb(85, 255, 127);")
        self.alarm_mash.setObjectName("alarm_mash")
        self.gridLayout_4.addWidget(self.alarm_mash, 0, 1, 1, 1)
        self.gridLayout_3.addWidget(self.pb_mash, 3, 1, 1, 1)
        self.pb_boil = QtWidgets.QGroupBox(self.centralwidget)
        self.pb_boil.setObjectName("pb_boil")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.pb_boil)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_6 = QtWidgets.QLabel(self.pb_boil)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.gridLayout_5.addWidget(self.label_6, 0, 0, 1, 1)
        self.lcd_boil_meas = QtWidgets.QLCDNumber(self.pb_boil)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcd_boil_meas.sizePolicy().hasHeightForWidth())
        self.lcd_boil_meas.setSizePolicy(sizePolicy)
        self.lcd_boil_meas.setSizeIncrement(QtCore.QSize(0, 0))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.lcd_boil_meas.setPalette(palette)
        self.lcd_boil_meas.setProperty("value", 100.0)
        self.lcd_boil_meas.setObjectName("lcd_boil_meas")
        self.gridLayout_5.addWidget(self.lcd_boil_meas, 1, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.pb_boil)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.gridLayout_5.addWidget(self.label_5, 2, 0, 1, 1)
        self.lcd_boil_set = QtWidgets.QLCDNumber(self.pb_boil)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 158, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 158, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.lcd_boil_set.setPalette(palette)
        self.lcd_boil_set.setLineWidth(1)
        self.lcd_boil_set.setSmallDecimalPoint(False)
        self.lcd_boil_set.setDigitCount(5)
        self.lcd_boil_set.setMode(QtWidgets.QLCDNumber.Dec)
        self.lcd_boil_set.setProperty("value", 80.0)
        self.lcd_boil_set.setProperty("intValue", 80)
        self.lcd_boil_set.setObjectName("lcd_boil_set")
        self.gridLayout_5.addWidget(self.lcd_boil_set, 3, 0, 1, 1)
        self.sldr_boil_set = QtWidgets.QSlider(self.pb_boil)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sldr_boil_set.sizePolicy().hasHeightForWidth())
        self.sldr_boil_set.setSizePolicy(sizePolicy)
        self.sldr_boil_set.setMinimum(80)
        self.sldr_boil_set.setMaximum(110)
        self.sldr_boil_set.setOrientation(QtCore.Qt.Vertical)
        self.sldr_boil_set.setObjectName("sldr_boil_set")
        self.gridLayout_5.addWidget(self.sldr_boil_set, 3, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.pb_boil)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.gridLayout_5.addWidget(self.label_2, 4, 0, 1, 1)
        self.lcd_boil_time = QtWidgets.QLCDNumber(self.pb_boil)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.lcd_boil_time.setPalette(palette)
        self.lcd_boil_time.setLineWidth(1)
        self.lcd_boil_time.setSmallDecimalPoint(False)
        self.lcd_boil_time.setDigitCount(5)
        self.lcd_boil_time.setMode(QtWidgets.QLCDNumber.Dec)
        self.lcd_boil_time.setProperty("value", 50.0)
        self.lcd_boil_time.setProperty("intValue", 50)
        self.lcd_boil_time.setObjectName("lcd_boil_time")
        self.gridLayout_5.addWidget(self.lcd_boil_time, 5, 0, 1, 1)
        self.sldr_boil_time = QtWidgets.QSlider(self.pb_boil)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sldr_boil_time.sizePolicy().hasHeightForWidth())
        self.sldr_boil_time.setSizePolicy(sizePolicy)
        self.sldr_boil_time.setMinimum(50)
        self.sldr_boil_time.setMaximum(90)
        self.sldr_boil_time.setOrientation(QtCore.Qt.Vertical)
        self.sldr_boil_time.setObjectName("sldr_boil_time")
        self.gridLayout_5.addWidget(self.sldr_boil_time, 5, 2, 1, 1)
        self.alarmbtn_boil = QtWidgets.QPushButton(self.pb_boil)
        self.alarmbtn_boil.setStyleSheet("background-color: rgb(0, 154, 74);")
        self.alarmbtn_boil.setCheckable(True)
        self.alarmbtn_boil.setAutoExclusive(True)
        self.alarmbtn_boil.setObjectName("alarmbtn_boil")
        self.gridLayout_5.addWidget(self.alarmbtn_boil, 6, 0, 1, 1)
        self.alarm_boil = QtWidgets.QToolButton(self.pb_boil)
        self.alarm_boil.setMaximumSize(QtCore.QSize(20, 20))
        self.alarm_boil.setStyleSheet("background-color: rgb(85, 255, 127);")
        self.alarm_boil.setObjectName("alarm_boil")
        self.gridLayout_5.addWidget(self.alarm_boil, 0, 2, 1, 1)
        self.gridLayout_3.addWidget(self.pb_boil, 3, 2, 1, 1)
        self.le_debug = QtWidgets.QLineEdit(self.centralwidget)
        self.le_debug.setObjectName("le_debug")
        self.gridLayout_3.addWidget(self.le_debug, 4, 0, 1, 3)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setProperty("value", 14)
        self.progressBar.setTextVisible(True)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout_3.addWidget(self.progressBar, 0, 0, 1, 3)
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser.sizePolicy().hasHeightForWidth())
        self.textBrowser.setSizePolicy(sizePolicy)
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout_3.addWidget(self.textBrowser, 1, 1, 2, 1)
        self.btn_start = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_start.sizePolicy().hasHeightForWidth())
        self.btn_start.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(28)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.btn_start.setFont(font)
        self.btn_start.setStyleSheet("background-color: rgb(255, 85, 0);")
        self.btn_start.setObjectName("btn_start")
        self.gridLayout_3.addWidget(self.btn_start, 1, 2, 2, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 960, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.sldr_mash_set.valueChanged['int'].connect(self.lcd_mash_set.display)
        self.sldr_mash_time.valueChanged['int'].connect(self.lcd_mash_time.display)
        self.sldr_boil_time.valueChanged['int'].connect(self.lcd_boil_time.display)
        self.sldr_boil_set.valueChanged['int'].connect(self.lcd_boil_set.display)
        self.sldr_sparge_set.valueChanged['int'].connect(self.lcd_sparge_set.display)
        self.sldr_strike_set.valueChanged['int'].connect(self.lcd_strike_set.display)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "RedCube Brewery"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Amps"))
        self.groupBox.setTitle(_translate("MainWindow", "Volts"))
        self.pb_hlt.setTitle(_translate("MainWindow", "Hot Liquor Tank"))
        self.label_9.setText(_translate("MainWindow", "Measured (°C)"))
        self.alarmbtn_hlt.setText(_translate("MainWindow", "Alarm ON"))
        self.alarm_hlt.setText(_translate("MainWindow", "..."))
        self.label_7.setText(_translate("MainWindow", "Sparge Water Set Point (°C)"))
        self.label_8.setText(_translate("MainWindow", "Strike Water Set Point (°C)"))
        self.pb_mash.setTitle(_translate("MainWindow", "Mash Tun"))
        self.label.setText(_translate("MainWindow", "Mash Time (min)"))
        self.label_4.setText(_translate("MainWindow", "Set Point (°C)"))
        self.alarmbtn_mash.setText(_translate("MainWindow", "Alarm ON"))
        self.label_3.setText(_translate("MainWindow", "Measured (°C)"))
        self.alarm_mash.setText(_translate("MainWindow", "..."))
        self.pb_boil.setTitle(_translate("MainWindow", "Boil"))
        self.label_6.setText(_translate("MainWindow", "Measured (°C)"))
        self.label_5.setText(_translate("MainWindow", "Set Point (°C)"))
        self.label_2.setText(_translate("MainWindow", "Boil Time (min)"))
        self.alarmbtn_boil.setText(_translate("MainWindow", "Alarm ON"))
        self.alarm_boil.setText(_translate("MainWindow", "..."))
        self.btn_start.setText(_translate("MainWindow", "START"))

